apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: lab4-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: grafana-pv
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
