apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: lab4-app
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31902
      protocol: TCP
      name: http
  selector:
    app: grafana
  type: NodePort
