server {
    listen 80;
    server_name _;            # под любым хостом

    root /usr/share/nginx/html;
    index index.html;

    # ► SPA-роуты
    location / {
        try_files $uri $uri/ /index.html;
    }

    # ► Прокси всех запросов, начинающихся с /api/
    location /api/ {
        proxy_pass http://backend.lab4-app.svc.cluster.local:5174/;      # Полное DNS-имя k8s-сервиса
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 300;  # Увеличиваем таймаут чтения
        proxy_connect_timeout 300;  # Увеличиваем таймаут подключения
    }
}