apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  namespace: app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
   limits:
    memory: "2Gi"
  requests:
    memory: "1Gi"
  storageClassName: standard 