apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: lab4-app
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: lab4-app
type: Opaque
data:
  url: aHR0cDovL21pbmlvOjkwMDA=
  access-key: bWluaW9hZG1pbg==
  secret-key: bWluaW9hZG1pbg==
