apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sanchous1000/frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://192.168.0.101:4001"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 20
          periodSeconds: 10 