{
 "title": "Производительность и обработка видео",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Производительность API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время выполнения запросов к БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_operation_latency_seconds_sum[5m]) / rate(db_operation_latency_seconds_count[5m])",
     "legendFormat": "{{operation}} {{table}}"
    }
   ]
  },
  {
   "title": "Время выполнения операций с MinIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(minio_operation_latency_seconds_sum[5m]) / rate(minio_operation_latency_seconds_count[5m])",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Размер ответов API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(api_response_size_bytes_sum[5m]) / rate(api_response_size_bytes_count[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "Обработка видео", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Время инференса модели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(model_inference_time_seconds_sum[5m]) / rate(model_inference_time_seconds_count[5m])",
     "legendFormat": "инференс модели"
    }
   ]
  },
  {
   "title": "Время конвертации видео",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(video_conversion_time_seconds_sum[5m]) / rate(video_conversion_time_seconds_count[5m])",
     "legendFormat": "конвертация видео"
    }
   ]
  },
  {
   "title": "Разрешение обрабатываемых видео",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(processed_video_pixels_histogram_sum[5m])/rate(processed_video_pixels_histogram_count[5m])",
     "legendFormat": "среднее количество пикселей"
    }
   ]
  },
  {
   "title": "Ошибки обработки видео",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(video_processing_errors_total[5m])) by (error_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  }
 ]
}