apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
  namespace: lab4-app
type: Opaque
data:
  token: "ODA3MTM2MTg1ODpBQUgyaWlQckpPbzFVY3VuR2Q1YmpUTjlCcVd4NlJhSXlLTQ=="
  user_ids: "NDc2MzEzOTYwLDc0MzUxNTIwNg=="
