apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
  namespace: lab4-app
type: Opaque
data:
  # Токен бота: 8071361858:AAH2iiPrJOo1UcunGd5bjTN9BqWx6RaIyKM
  token: "ODA3MTM2MTg1ODpBQUgyaWlQckpPbzFVY3VuR2Q1YmpUTjlCcVd4NlJhSXlLTQ=="
  # ID пользователей: 476313960,743515206
  user_ids: "NDc2MzEzOTYwLDc0MzUxNTIwNg=="
