apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-lab4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/k8s/minio-pv-lab4
