apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: lab4-app
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    targetPort: web
      nodePort: 31903
    protocol: TCP
    name: http
  selector:
    app: prometheus
  type: NodePort
