apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  namespace: lab4-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: storage-pv
