[servers]
docker_host ansible_host=89.169.142.40 ansible_port=22

[servers:vars]
ansible_user=terra
ansible_ssh_pass=terra
ansible_become=yes
ansible_become_method=sudo
ansible_become_pass=terra
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'