name: CI проекта

on:
  push:
    branches: [main, lab4]
  pull_request:
    branches: [main, lab4]

jobs:
  telegram-start-notification:
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send Telegram start notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_IDS: ${{ secrets.TELEGRAM_USER_IDS }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
        run: |
          MESSAGE=$(printf "📦 CI/CD Workflow: ${GITHUB_WORKFLOW}\n▶️ *Старт* на ветке \`${GITHUB_REF}\` (коммит \`${GITHUB_SHA::8}\`).\n")
          MESSAGE+=$(printf "\n")

          USERS=${{ secrets.TELEGRAM_USER_IDS }}
          IFS=',' read -ra USER_IDS <<< "$USERS"
          for user_id in "${USER_IDS[@]}"; do
            echo "Sending start notification to user ID: $user_id"
            curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${user_id} -d text="${MESSAGE}" -d parse_mode=Markdown || true
          done

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view
          kubectl cluster-info

      - name: Make update script executable
        run: chmod +x project/kubernetes/update-app.sh

      - name: Run Deployment Script
        run: |
          cd project
          ./kubernetes/update-app.sh

  deploy-services:
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view
          kubectl cluster-info

      - name: Create PV directories
        run: |
          # Применяем DaemonSet для создания директорий
          kubectl apply -f project/kubernetes/scripts/create-pv-dirs.yaml
          # Ждем пока поды запустятся
          kubectl wait --for=condition=ready pod -l name=create-pv-dirs -n lab4-app --timeout=60s
          # Даем время на создание директорий
          sleep 10
          # Удаляем DaemonSet
          kubectl delete -f project/kubernetes/scripts/create-pv-dirs.yaml

      - name: Make setup script executable
        run: chmod +x project/kubernetes/setup-services.sh

      - name: Run Services Setup Script
        run: |
          cd project/kubernetes
          ./setup-services.sh

  telegram-notification:
    needs: [deploy, deploy-services]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send Telegram notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_IDS: ${{ secrets.TELEGRAM_USER_IDS }}
          GITHUB_RUN_STATUS: ${{ needs.deploy.result == 'success' && needs.deploy-services.result == 'success' && 'success' || 'failure' }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_RUN_URL: ${{ github.event.pull_request.html_url || github.event.compare.html_url || github.event.head_commit.url || github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          MESSAGE=$(printf "📦 CI/CD Workflow: ${GITHUB_WORKFLOW}\n")

          if [ "$GITHUB_RUN_STATUS" == "success" ]; then
            MESSAGE+=$(printf "\n✅ *Статус: УСПЕХ*\n")
          else
            MESSAGE+=$(printf "\n❌ *Статус: ОШИБКА*\n")
          fi

          MESSAGE+=$(printf "\n🌳 *Ветка:* \`${GITHUB_REF}\`\n🛠️ *Коммит:* \`${GITHUB_SHA::8}\`\n🔗 *Подробнее:* [Ссылка на запуск](${GITHUB_RUN_URL})\n")

          USERS=${{ secrets.TELEGRAM_USER_IDS }}
          IFS=',' read -ra USER_IDS <<< "$USERS"
          for user_id in "${USER_IDS[@]}"; do
            echo "Sending notification to user ID: $user_id"
            curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${user_id} -d text="${MESSAGE}" -d parse_mode=Markdown || true
          done
